spring:
  application:
    name: hotelapi
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hoteldbv2
    username: postgres
    password: postgres
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      file-size-threshold: 2KB
      max-request-size: 215MB
springdoc:
  override-with-generic-response: false
file:
  directory: /home/vitor/arquivosx/

