spring:
  application:
    name: hotelapi
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      file-size-threshold: 2KB
      max-request-size: 215MB
springdoc:
  override-with-generic-response: false
